version: '3.4'

services:
    sqlserver:
        container_name: sql-server 
        image: sql-server
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=Dd8f6fDZ
          - DATABASE=ToDo
        ports:  
          - '3010:1433'
        build:
            context: .
            dockerfile: ./ToDo-API/scripts/sql-server/Dockerfile
                
    backend:
        container_name: backend
        image: backend
        restart: always
        build: ./ToDo-API/
        ports:
          - "64978:80"
        depends_on:
          - sqlserver

    frontend:
        container_name: frontend
        image: frontend
        build: ./ToDo-UI/
        ports:
          - '5555:80'
